### ISSUE TITLE
EdgeF4 Menu icons and weapons overlap. Slib creates error

### ISSUE THREAD

**Issue by APersonThatLikesMemes** [Shark-vil/slib-garrysmod#45]
So EdgeF4 Menu is a paid addon that uses this addon.
On the details page for a job whenever I try to click on icons for the details or weapons it overlaps and slib creates this error
![fbd5c7da4b910ec3a04f939fea58d30f](https://user-images.githubusercontent.com/43283172/144646538-cb5bfe08-0baa-4234-9796-749fad9dc6b6.png)
I used both the github version and the workshop version of this. I contacted EdgeF4's creator and he told me to submit a ticket here.
If you can fix this that would be great
Thanks

**Comment by Shark-vil** [comment]
> 

Hello. Can you show these code snippets? I want to understand why this is happening
![chrome_0SXIULmq7Z](https://user-images.githubusercontent.com/13109606/144649015-e788ba5b-3e26-46bb-bf83-7a817d2c19a0.png)

Of course, I understand the mistake without this, but it will be good if I am sure of the reason. :)

**Comment by Shark-vil** [comment]
If you do not want to distribute the code, you can go to my discord server and open a ticket, the correspondence will be available only between us.

**Comment by APersonThatLikesMemes** [comment]
I hope these help. If you need the actual file I'll send it... if that's legal lol.
![line85cl_widgetcarousel](https://user-images.githubusercontent.com/43283172/144652875-fe9fc3e4-45c3-40e7-8e4c-606fc0afac98.PNG)
![Line68cl_widgetcarousel](https://user-images.githubusercontent.com/43283172/144652877-71582110-0cd9-4f01-b766-f7aac981fd02.PNG)
![Line200cl_widgetcarousel](https://user-images.githubusercontent.com/43283172/144652878-07033d45-4865-4f07-989b-e0ab70d728cf.PNG)

**Comment by APersonThatLikesMemes** [comment]
Or... I could've just copied and pasted the code... Oh well. Whatever you need from me I'll give ya
