### ISSUE TITLE
SLibrary Conflict with Food/Household items pack

### ISSUE THREAD

**Issue by jimmy9034** [Shark-vil/slib-garrysmod#51]
**Describe the bug**
SLibrary conflict with Food/Household items pack?

**Situation for the error to occur**
Spawning in certain items (example: models/foodnhouseholditems/fishbass.mdl) causes errors to appear.

**Screenshots or video**
[LUA - SLibrary] lua/slib_framework/extension/gui/cl_listener.lua:4: attempt to index field 'sgui_listeners' (a nil value)
  1. ExecuteListener - lua/slib_framework/extension/gui/cl_listener.lua:4
   2. unknown - lua/slib_framework/extension/gui/cl_listener.lua:29
    3. ExecuteListener - lua/slib_framework/extension/gui/cl_listener.lua:5
     4. DoClick - lua/slib_framework/extension/gui/cl_listener.lua:29
      5. unknown - lua/vgui/dlabel.lua:237 (x13)

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**
I can spawn in seafood through the addon folder but I have a customer folder in which I have the food organised in by groups. (Which I get error from when trying to spawn in.) Spawning through search menu also works.

I also have other custom folders and they work perfectly fine without any issues.

**Comment by Shark-vil** [comment]
Most likely fixed. If the issue persists, open the issue again.
