### ISSUE TITLE
strange 'getdatatable' nil value error spamming console

### ISSUE THREAD

**Issue by ZayaJames** [Shark-vil/slib-garrysmod#58]
**Describe the bug**
This error keeps popping up in console
**Situation for the error to occur**
Describe in detail the situation when the error occurs. Check this situation with the addon enabled and disabled before creating a ticket. Complaints in the format "*Your addon is breaking the game, please fix it*" or "*It doesn't work for me*" will be rejected.
no clear cause, spamming the console and generally being annoying
**Screenshots or video**
If possible, add a video or screenshots that show the error.
![lua_error](https://user-images.githubusercontent.com/40363838/177266227-02c98492-6b00-464b-9042-0eda81b639ce.PNG)
**Desktop:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]
windows 10 home version 21H2
**Additional context**
It might be caused by another addon called "Background NPCS"

**Comment by Shark-vil** [comment]
Should be fixed now.
